### ISSUE TITLE
No positional encoding in transformer implementation

### ISSUE THREAD

**Issue by HoaiDuyLe** [wenliangdai/Multimodal-End2end-Sparse#16]
Thank you very much for the code you shared.

In the paper, you said that you use the Transformer to encode the sequential representation of sequences of visual (and acoustic) representation. But I am confused about there being no positional encoding in the transformer_encoder.py file (this line is commented "# inputs = self.pos_encoder(inputs)" ).  Could you clarify this?

**Comment by wenliangdai** [comment]
Hi @HoaiDuyLe, thanks for your interest in our paper. 

For the positional encoding, we did an ablation in our experiments, and with/without the positional encoding does not influence much on the downstream datasets we used. That's why we just commented it out. However, it may have some effects on other datasets. Therefore, please check https://pytorch.org/tutorials/beginner/transformer_tutorial.html and the PositionalEncoding in it. It can be directly incorporated into our code.
